language: node_js
node_js:
- '0.11'
- '0.10'
services:
- redis-server
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: Kzbb0ooNWltO9xAnNTkzWwU8sLSFbOGP7f88agl+MvLd8QjiBZ4khBsRHPjSVTjUjUQxM/R0eGRv8tMJma1++R+iBmp/vadJSvLVam2op3O6+rXxFX8NmUXXbgUCdSEei0LMUinVstHy4isO9AGIbolvVy+SO9MDYtyee8Nw3Yk=
