language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
services:
- redis-server
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: X1/K+w7MPz0SJULxyfiOEJXZV4bkE0sdz+ylR0HBxZSmPSo8okJ7BXbHSUhRK1ScJkhO0Phh5HVby59Hk4NL3a2WdspDndimJ0r9z1tfzoeiuEKxNAFe0jl/kCxIjDP20L1rJ6JnzFQlZ71Kxza7Rlg4ViGVUFvcgLixsC+/1j8=
